version: "3.8"
volumes:
  db-data:
services:
  webserver:
    build:
      context: ./bin/${PHPVERSION}
    container_name: ${PHPVERSION}
    restart: always
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini:cached
      - ${VHOSTS_DIR-./config/apache2/sites}:/etc/apache2/sites-available:cached
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
    environment:
        PMA_PORT: ${HOST_MACHINE_PMA_PORT}
  database:
    build:
      context: "./bin/${DATABASE}"
    container_name: 'database'
    restart: always
    ports:
      - "${HOST_MACHINE_IP_ADDRESS}:${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: 'phpmyadmin'
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '${HOST_MACHINE_PMA_PORT}:80'
    volumes:
      - /sessions
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini:cached
  redis:
    container_name: 'redis'
    image: redis:latest
    ports:
      - "${HOST_MACHINE_IP_ADDRESS}:${HOST_MACHINE_REDIS_PORT}:6379"
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui